import { Geist, Geist_Mono, Noto_Sans_Bengali, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "../components/page/Footer/footer";
import Navbar from "@/components/page/Navbar/Navbar";
import AuthProvider from "@/Context/AuthProvider/AuthProvider";
import { ToastContainer } from "react-toastify";
import ScrollUp from "@/components/ScrollUp/ScrollUp";



const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const notoBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  variable: "--font-noto-bengali",
  weight: ["400", "500", "600", "700"],
});


export const metadata = {
  title: "EduSmart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html  lang="en" suppressHydrationWarning={true}>
       
      <body
          className={`${poppins.variable} ${notoBengali.variable} font-sans antialiased`}
        suppressHydrationWarning={true}
     
      >
      
       
        <AuthProvider>
          <div className="bg-background">
            <Navbar></Navbar>
            
       
            <div className="min-h-[calc(100vh-479px)]">
              {children}
            </div>
            <Footer></Footer>
          </div>
           <ScrollUp></ScrollUp>
          <ToastContainer />
        </AuthProvider>
        

      </body>
    </html>
  );
}
