import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Navbar from "@/components/page/Navbar/Navbar";
import AuthProvider from "@/Context/AuthProvider/AuthProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EduSmart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="bg-background">
            <Navbar></Navbar>
            <div className="min-h-[calc(100vh-479px)]">
              {children}
            </div>
            <Footer></Footer>
          </div>
          <ToastContainer />
        </AuthProvider>

      </body>
    </html>
  );
}
